[package]
name = "block_cryptography"
version = "0.1.0"
authors = ["Jacob Weir"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.17.0-alpha.4"
